Repository next-level-dev-pl/smart-route, pull requests merged in 2025-02, with the labels that each got.

#5 Base app created. Lombok added as dependency.
  .gitattributes
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/pl/nextleveldev/smart_route/SmartRouteApplication.java
  src/main/resources/application.properties
  src/test/java/pl/nextleveldev/smart_route/SmartRouteApplicationTests.java
Labels: enhancement

#7 3-add-spock-to-app
  build.gradle
  src/test/groovy/pl/nextleveldev/smart_route/ApplicationContextLoadSpec.groovy
  src/test/java/pl/nextleveldev/smart_route/SmartRouteApplicationTests.java
Labels: enhancement, good first issue

#27 Docs/25 branch naming conventions
  docs/UW-Warszawa-API/generowanie-docs-api.md
  docs/UW-Warszawa-API/informacje-1.md
  docs/UW-Warszawa-API/informacje-2.md
  docs/UW-Warszawa-API/informacje-3.md
  docs/UW-Warszawa-API/informacje-4.md
  docs/UW-Warszawa-API/informacje-5.md
  docs/UW-Warszawa-API/informacje-6.md
  docs/git/branch-naming-conventions.md
Labels: documentation

#29 Add to CI test checking before merge to main
  .github/workflows/test.yml
Labels: configuration

#43 Decorated README
  README.md
  docs/next-level-dev/README.md
  docs/public/next-level-dev-logo.png
  docs/public/smart-route-logo.png
Labels: documentation
